#! /bin/sh

sxhkd &
polybar sticks-bspwm &
nitrogen --restore &
picom -b &
nm-applet &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           2
bspc config focused_border_color "#16A086"

bspc config split_ratio          0.53
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a arduino state=floating follow=on
bspc rule -a android-studio state=floating follow=on
